### PR TITLE
Many changes

### PR DESCRIPTION
**Pull request by Rafagd**
I'm opening this request so I can send you some code back in exchange of using yaam to manage some PBX servers. I'm submitting them into a separated branch (`rafagd_changes`), so you can pick and choose what changes you want to keep and what you want to discard before merging to master.

It seems that this code was submitted in midst of a migration of template
engines, so I did my best to fit the old code to the newer templating scheme.
There were also some parts that felt unimplemented, so I took the liberty of
implementing them, like the user management screen. I've also added a user group
management screen that doubles as permission group. If you're on the admin group
you'll be allowed to see admin-only plugins, else you'll only see non-admin stuff.

I've also fixed the pagination tool on the CDR plugin (which didn't respected
previous search results) and added a date search field.

You can also find the schema for the database on root/database.sql.

There's also a bit of lazy coding I did on the user's profile screen, where he can change some of his own information. The validation that doesn't let he change the user being edited is javascript-only at this moment.

### CODE REVIEW

**Comment by Rafagd** [comment]
I thought you could submit into a new branch, but that's not a option. So just be aware that you may need to revert some changes if you dislike them.

**Comment by bfrigon** [comment]
I'm sorry, i'm not ignoring you. I did not get the chance to test this yet, i have been busy lately. I looked at it and it looks very good. I will merge the changes you made for sure.

If you are interested, i can give you write access to my repo so you can continue to develop it there. 

These are the main guidelines i wanted to follow when i started this project : 
1- Keep the interface lightweight.
2- Make it usable as much as possible when javascript is disabled. JS shoud be used to enhance the functionality but not rely on it.

Also, don't hesitate to add your name to the file header you contribute to.

**Comment by Rafagd** [comment]
Thanks, I'll send you more changes as soon as I can to fix the lazy coding soon.

**Comment by Rafagd** [comment]
Unfortunatelly for contractual reasons I'll be unable to contribute further into VoIP-related stuff. This isn't directly VoIP, but I'd rather not risk losing a scholarship.

Thanks for accepting my changes.

**Pull request merged**
